## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file using_sagetex.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1269 = Integer(1269); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_22 = Integer(22); _sage_const_21 = Integer(21); _sage_const_27 = Integer(27)## This file (using_sagetex.sagetex.sage) was *autogenerated* from using_sagetex.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('using_sagetex', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
try:
 _st_.inline(_sage_const_0 , latex(number_of_partitions(_sage_const_1269 )))
except:
 _st_.goboom(_sage_const_8 )
_st_.blockbegin()
try:
   __tmp__=var("x"); f = symbolic_expression(exp(x) * sin(_sage_const_2 *x)).function(x)
except:
 _st_.goboom(_sage_const_16 )
_st_.blockend()
try:
 _st_.inline(_sage_const_1 , latex(f(x)))
except:
 _st_.goboom(_sage_const_21 )
try:
 _st_.inline(_sage_const_2 , latex(diff(f, x, _sage_const_2 )(x)))
except:
 _st_.goboom(_sage_const_22 )
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(f, -_sage_const_1 , _sage_const_1 ))
except:
 _st_.goboom(_sage_const_27 )
_st_.endofdoc()
